from html import escape
from pathlib import Path
import json

ROOT = Path(__file__).parent
games = json.loads((ROOT / 'games.json').read_text())
CATEGORY = {
    'ARCADE':'格斗', 'MAIN':'格斗', 'VERSUS':'格斗', 'SCORE':'格斗', 'LAB':'格斗',
    'NOVEL':'叙事', 'HERO':'叙事', 'RUN':'动作', 'DEFENSE':'策略', 'MUSIC':'节奏',
    'PUZZLE':'解谜', 'SIMULATION':'模拟', 'SALVAGE':'探索', 'TRADING':'经营',
    'TACTICAL':'策略', 'STEALTH':'潜行', 'NEW':'生存', 'RACING':'竞速',
    'INSPECTION':'模拟', 'RESCUE':'救援', 'DINER':'经营', 'COMPANION':'休闲',
    'PINBALL':'街机', 'SPORTS':'运动', 'SHOOTER':'射击', 'EXPLORER':'探索', 'CASE':'推理',
}
for item in games:
    item['category'] = CATEGORY.get(item['pill'], item['pill'])
by_name = {item['name']: item for item in games}

def get(name):
    return by_name[name]

def attrs(item):
    return {k: escape(str(item[k]), quote=True) for k in ('url','name','tag','desc','category')}

def signal_card(item, index):
    a = attrs(item)
    return f'''<a class="signal-card cab" href="{a['url']}" data-category="{a['category']}" data-name="{a['name']}" data-tag="{a['tag']}" aria-label="锁定并进入 {a['name']}">
      <span class="signal-id">SIG-{index:02d}</span><span class="signal-led"></span><span class="signal-type">{a['category']} / {a['tag']}</span><strong>{a['name']}</strong><small>{a['desc']}</small><span class="signal-open">LOCK <b>↗</b></span>
    </a>'''

def relay_card(item, index):
    a = attrs(item)
    return f'''<a class="relay-card cab" href="{a['url']}" data-category="{a['category']}" data-name="{a['name']}" data-tag="{a['tag']}" aria-label="锁定并进入 {a['name']}">
      <span class="relay-id">SIG-{index:02d}</span><span><em>{a['category']} · {a['tag']}</em><strong>{a['name']}</strong><small>{a['desc']}</small></span><b class="relay-arrow">↗</b>
    </a>'''

hero_game = get('霓虹幸存者')
featured = [(get('星港调查员'), 29), (get('星港调度'), 13), (get('量子弹珠'), 24)]
categories = []
for item in games:
    if item['category'] not in categories:
        categories.append(item['category'])
filters = ''.join(f'<button class="filter" data-filter="{escape(c)}">{escape(c)}</button>' for c in categories)
signals = ''.join(signal_card(item, i) for i, item in enumerate(games, 1))
relays = ''.join(relay_card(item, index) for item, index in featured)
hero = attrs(hero_game)

html = r'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#02040c">
<title>星港游戏厅 · SIGNAL CONTROL</title>
<meta name="description" content="星港游戏厅 SIGNAL CONTROL：锁定一枚游戏信号，进入下一段未来。">
<style>
:root{
  --void:#02040c;--deep:#050b18;--panel:rgba(5,16,32,.74);--panel-solid:#071426;
  --cyan:#54f3ff;--cyan-2:#1ba5c0;--violet:#987cff;--pink:#ff3fb9;--lime:#a2ffd0;--amber:#ffc35c;
  --white:#e5f6ff;--muted:#7795aa;--faint:#38546d;--line:rgba(84,243,255,.2);
  --mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;
  --sans:ui-sans-serif,-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif;
  --mx:0;--my:0;
}
*{box-sizing:border-box}
html{background:var(--void);scroll-behavior:smooth}
body{margin:0;min-width:320px;overflow-x:hidden;background:var(--void);color:var(--white);font-family:var(--sans);-webkit-font-smoothing:antialiased}
a{color:inherit;text-decoration:none}button{font:inherit;color:inherit;cursor:pointer}
#starfield{position:fixed;z-index:0;inset:0;width:100%;height:100%;background:#02040c;pointer-events:none}
body:before{content:"";position:fixed;z-index:1;inset:0;pointer-events:none;background:radial-gradient(ellipse at calc(50% + var(--mx)*25%) calc(38% + var(--my)*18%),rgba(24,112,157,.16),transparent 35%),linear-gradient(180deg,transparent 0 68%,rgba(1,3,9,.82) 100%)}
body:after{content:"";position:fixed;z-index:4;inset:0;pointer-events:none;opacity:.16;mix-blend-mode:screen;background:repeating-linear-gradient(180deg,rgba(84,243,255,.055) 0 1px,transparent 1px 5px)}
.page{position:relative;z-index:3;width:min(1420px,calc(100% - 52px));margin:0 auto}
.hud-top{height:70px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);position:relative}.brand{display:flex;align-items:center;gap:13px}.brand-core{width:33px;height:33px;border:1px solid var(--cyan);border-radius:50%;display:grid;place-items:center;color:var(--cyan);font:700 11px var(--mono);position:relative;box-shadow:0 0 18px rgba(84,243,255,.35)}.brand-core:before,.brand-core:after{content:"";position:absolute;border:1px solid var(--cyan-2);border-radius:50%;transform:rotate(45deg)}.brand-core:before{inset:-6px 7px}.brand-core:after{inset:7px -6px}.brand-copy b{display:block;font-size:14px;letter-spacing:.2em}.brand-copy small{display:block;margin-top:4px;color:var(--faint);font:9px var(--mono);letter-spacing:.18em}.top-status{display:flex;align-items:center;gap:21px;color:var(--muted);font:9px var(--mono);letter-spacing:.13em}.top-status b{color:var(--lime);font-weight:500}.online-dot{display:inline-block;width:6px;height:6px;margin-right:7px;border-radius:50%;background:var(--lime);box-shadow:0 0 12px var(--lime)}
.control-room{min-height:calc(100vh - 70px);display:grid;grid-template-columns:260px minmax(520px,1fr) 260px;gap:28px;align-items:center;padding:28px 0 65px;position:relative}.control-room:before{content:"";position:absolute;z-index:-1;left:20%;right:20%;bottom:7%;height:1px;background:linear-gradient(90deg,transparent,var(--cyan-2),transparent);box-shadow:0 0 26px var(--cyan-2)}
.left-deck{align-self:center}.eyebrow{display:flex;align-items:center;gap:10px;color:var(--cyan);font:10px var(--mono);letter-spacing:.17em}.eyebrow:before{content:"";width:28px;height:1px;background:var(--cyan);box-shadow:0 0 12px var(--cyan)}.left-deck h1{font-size:clamp(44px,5.2vw,76px);line-height:1.02;letter-spacing:-.1em;margin:21px 0 19px;font-weight:900}.left-deck h1 span{display:block;color:var(--cyan);text-shadow:0 0 20px rgba(84,243,255,.6),2px 0 rgba(255,63,185,.2)}.lede{color:var(--muted);font-size:14px;line-height:1.85;margin:0}.lede b{color:var(--white);font-weight:600}.actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:24px}.action{display:inline-flex;align-items:center;gap:12px;padding:11px 13px;border:1px solid var(--line);background:rgba(5,17,33,.72);font-size:11px;transition:.2s}.action.primary{color:#02101b;background:var(--cyan);border-color:var(--cyan);font-weight:900;box-shadow:0 0 22px rgba(84,243,255,.22)}.action:hover{transform:translateY(-3px);border-color:var(--cyan);box-shadow:0 0 18px rgba(84,243,255,.2)}.readouts{display:grid;grid-template-columns:repeat(2,1fr);gap:12px 15px;margin-top:32px;padding-top:17px;border-top:1px solid var(--line)}.readout b{display:block;color:var(--white);font:700 17px var(--mono)}.readout small{display:block;margin-top:5px;color:var(--faint);font:8px var(--mono);letter-spacing:.08em}
.core-stage{height:min(690px,68vw);min-height:545px;position:relative;display:grid;place-items:center;perspective:1100px}.stage-caption,.stage-coordinates{position:absolute;color:var(--muted);font:9px var(--mono);letter-spacing:.14em}.stage-caption{left:2%;top:3%}.stage-caption:before{content:"◆ ";color:var(--pink)}.stage-coordinates{right:2%;bottom:2%;color:var(--cyan-2)}.stage-cross{position:absolute;left:50%;top:50%;width:calc(100% - 80px);height:calc(100% - 80px);transform:translate(-50%,-50%);opacity:.27;background:linear-gradient(90deg,transparent 49.8%,var(--cyan-2) 50%,transparent 50.2%),linear-gradient(0deg,transparent 49.8%,var(--cyan-2) 50%,transparent 50.2%);mask-image:radial-gradient(circle,#000 0 35%,transparent 72%)}
.orbit-core{width:min(590px,98%);aspect-ratio:1;position:relative;transform:rotateX(calc(59deg + var(--my)*-7deg)) rotateZ(calc(var(--mx)*3deg));transform-style:preserve-3d;transition:transform .18s ease-out}.orbit-ring{position:absolute;inset:5%;border:1px solid rgba(84,243,255,.45);border-radius:50%;transform:rotateZ(8deg);box-shadow:0 0 0 15px rgba(84,243,255,.025),0 0 0 36px rgba(84,243,255,.018),inset 0 0 25px rgba(84,243,255,.1);animation:orbit-a 13s linear infinite}.orbit-ring:before,.orbit-ring:after{content:"";position:absolute;inset:11%;border:1px dashed rgba(152,124,255,.42);border-radius:50%}.orbit-ring:after{inset:30%;border-style:solid;border-color:rgba(255,63,185,.35)}.orbit-ring.two{inset:14%;transform:rotateX(62deg) rotateY(12deg);border-color:rgba(255,63,185,.3);animation:orbit-b 9s linear infinite reverse}.orbit-ring.three{inset:22%;transform:rotateX(72deg) rotateZ(55deg);border-color:rgba(162,255,208,.32);animation:orbit-a 6s linear infinite reverse}@keyframes orbit-a{to{transform:rotateZ(368deg)}}@keyframes orbit-b{to{transform:rotateX(62deg) rotateY(12deg) rotateZ(-352deg)}}
.orbit-core:before{content:"";position:absolute;inset:18%;border-radius:50%;background:radial-gradient(circle,rgba(84,243,255,.18),transparent 53%);filter:blur(12px);transform:translateZ(-25px)}.core-sphere{position:absolute;z-index:4;left:50%;top:50%;width:220px;height:220px;transform:translate(-50%,-50%) rotateX(-59deg) rotateY(calc(var(--mx)*18deg));border:1px solid rgba(84,243,255,.78);border-radius:50%;background:radial-gradient(circle at 36% 29%,#d8ffff 0 1%,#38cbdc 3%,#07526f 16%,#031322 54%,#01050d 72%),conic-gradient(from 40deg,transparent,#54f3ff,transparent 20%,#ff3fb9,transparent 60%);box-shadow:0 0 16px var(--cyan),0 0 65px rgba(84,243,255,.46),inset -20px -18px 55px rgba(255,63,185,.22),inset 22px 20px 45px rgba(84,243,255,.32);overflow:hidden;transition:transform .2s}.core-sphere:before{content:"";position:absolute;inset:13%;border:1px solid rgba(162,255,208,.52);border-radius:50%;background:linear-gradient(90deg,transparent 49.5%,rgba(162,255,208,.5) 50%,transparent 50.5%),linear-gradient(0deg,transparent 49.5%,rgba(162,255,208,.5) 50%,transparent 50.5%);box-shadow:inset 0 0 25px rgba(84,243,255,.34)}.core-sphere:after{content:"";position:absolute;left:-10%;right:-10%;top:47%;height:2px;background:linear-gradient(90deg,transparent,var(--white),transparent);box-shadow:0 0 16px var(--white);animation:core-scan 2.9s linear infinite}@keyframes core-scan{0%{transform:translateY(-95px);opacity:0}25%,75%{opacity:.8}100%{transform:translateY(95px);opacity:0}}
.core-eye{position:absolute;z-index:5;left:50%;top:50%;transform:translate(-50%,-50%) rotateX(-59deg);text-align:center;color:var(--white);font:900 17px var(--mono);letter-spacing:.16em;text-shadow:0 0 14px var(--cyan)}.core-eye small{display:block;margin-top:7px;color:var(--lime);font-size:7px;letter-spacing:.17em}.node{position:absolute;z-index:6;padding:7px 9px;border:1px solid rgba(84,243,255,.45);background:rgba(2,11,24,.84);color:var(--cyan);font:8px var(--mono);letter-spacing:.1em;white-space:nowrap;box-shadow:0 0 14px rgba(84,243,255,.11);transform:rotateX(-59deg)}.node:before{content:"";position:absolute;width:7px;height:7px;border:1px solid currentColor;border-radius:50%;box-shadow:0 0 10px currentColor}.node.a{left:13%;top:30%;color:var(--pink)}.node.a:before{right:-25px;top:11px}.node.b{right:9%;top:54%;color:var(--lime)}.node.b:before{left:-25px;top:11px}.node.c{left:24%;bottom:17%;color:var(--amber)}.node.c:before{right:-25px;top:11px}
.telemetry{position:absolute;z-index:8;padding:8px 9px;border:1px solid rgba(84,243,255,.2);background:rgba(2,9,20,.68);font:8px/1.65 var(--mono);letter-spacing:.07em;color:var(--faint)}.telemetry b{display:block;color:var(--cyan);font-size:9px}.telemetry.left{left:0;top:26%}.telemetry.right{right:0;top:26%;text-align:right}.telemetry.bottom{left:4%;bottom:10%}
.signal-console{position:absolute;z-index:10;left:50%;bottom:5%;transform:translateX(-50%);width:min(390px,76%);padding:11px 13px;display:flex;align-items:center;gap:11px;border:1px solid rgba(255,63,185,.65);background:linear-gradient(90deg,rgba(31,5,31,.9),rgba(3,14,28,.92));box-shadow:0 0 26px rgba(255,63,185,.14);transition:.2s}.signal-console:hover{border-color:var(--cyan);box-shadow:0 0 28px rgba(84,243,255,.2);transform:translateX(-50%) translateY(-3px)}.lock-mark{width:27px;height:27px;display:grid;place-items:center;border:1px solid var(--pink);color:var(--pink);font:14px var(--mono)}.signal-console small{display:block;color:var(--pink);font:8px var(--mono);letter-spacing:.12em}.signal-console strong{display:block;margin-top:3px;font-size:14px}.signal-console em{margin-left:auto;color:var(--lime);font:8px var(--mono);font-style:normal}
.right-deck{align-self:center}.deck-label{display:flex;align-items:center;justify-content:space-between;padding-bottom:12px;border-bottom:1px solid var(--line);color:var(--muted);font:9px var(--mono);letter-spacing:.13em}.deck-label b{color:var(--lime);font-weight:500}.system-box{margin-top:13px;padding:14px;border:1px solid var(--line);background:var(--panel);backdrop-filter:blur(8px)}.system-box h2{margin:0;color:var(--cyan);font:11px var(--mono);letter-spacing:.14em}.system-box p{margin:11px 0 0;color:var(--muted);font-size:11px;line-height:1.7}.bar{height:3px;margin-top:14px;background:rgba(84,243,255,.12);overflow:hidden}.bar i{display:block;width:76%;height:100%;background:linear-gradient(90deg,var(--cyan),var(--violet));box-shadow:0 0 10px var(--cyan)}.metric-line{display:flex;justify-content:space-between;margin-top:9px;color:var(--faint);font:8px var(--mono)}.metric-line b{color:var(--white);font-weight:500}.relay-title{margin:29px 0 9px;color:var(--muted);font:9px var(--mono);letter-spacing:.13em}.relay-list{display:grid;gap:7px}.relay-card{display:grid;grid-template-columns:42px 1fr 17px;align-items:center;gap:8px;padding:10px;border:1px solid rgba(84,243,255,.17);background:rgba(3,14,28,.7);transition:.2s}.relay-card:hover{border-color:var(--cyan);background:rgba(6,30,48,.9);transform:translateX(-4px)}.relay-id{color:var(--violet);font:8px var(--mono)}.relay-card em{display:block;color:var(--faint);font:8px var(--mono);font-style:normal}.relay-card strong{display:block;margin-top:3px;font-size:13px}.relay-card small{display:block;margin-top:3px;color:var(--muted);font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.relay-arrow{color:var(--cyan);font:16px var(--mono)}
.signals-section{padding:27px 0 80px;border-top:1px solid var(--line)}.signals-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:18px}.signals-head h2{margin:0;font-size:26px;letter-spacing:-.06em}.signals-head p{margin:0;color:var(--faint);font:9px var(--mono);letter-spacing:.13em}.filters{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:16px}.filter{padding:7px 10px;border:1px solid rgba(84,243,255,.17);background:rgba(3,13,26,.74);color:var(--muted);font-size:10px;transition:.18s}.filter:hover,.filter.active{background:var(--cyan);border-color:var(--cyan);color:#02101a;box-shadow:0 0 13px rgba(84,243,255,.25)}.signal-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.signal-card{min-height:132px;position:relative;padding:15px;border:1px solid rgba(84,243,255,.14);background:linear-gradient(135deg,rgba(5,27,46,.84),rgba(2,10,21,.88));overflow:hidden;transition:.2s}.signal-card:before{content:"";position:absolute;right:-31px;top:-30px;width:118px;height:118px;border:1px solid rgba(84,243,255,.12);border-radius:50%;box-shadow:0 0 0 17px rgba(84,243,255,.017),0 0 0 35px rgba(84,243,255,.012)}.signal-card:hover{border-color:var(--cyan);transform:translateY(-4px);box-shadow:0 0 22px rgba(84,243,255,.13)}.signal-card:hover .signal-led{background:var(--pink);box-shadow:0 0 13px var(--pink)}.signal-card[hidden]{display:none}.signal-id{color:var(--faint);font:8px var(--mono);letter-spacing:.12em}.signal-led{position:absolute;right:15px;top:16px;width:6px;height:6px;border-radius:50%;background:var(--lime);box-shadow:0 0 8px var(--lime);transition:.2s}.signal-type{display:block;margin-top:20px;color:var(--cyan);font:8px var(--mono);letter-spacing:.06em}.signal-card strong{display:block;margin:7px 0 5px;font-size:17px}.signal-card small{display:block;max-width:88%;color:var(--muted);font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.signal-open{position:absolute;right:14px;bottom:13px;color:var(--faint);font:8px var(--mono)}.signal-open b{margin-left:4px;color:var(--cyan);font-size:14px}.empty{grid-column:1/-1;padding:30px;text-align:center;border:1px dashed var(--line);color:var(--muted);font:11px var(--mono)}.footer{display:flex;justify-content:space-between;gap:20px;padding:19px 0 28px;border-top:1px solid var(--line);color:var(--faint);font:8px var(--mono);letter-spacing:.08em}.footer b{color:var(--lime);font-weight:500}.cab:focus-visible,.action:focus-visible,.filter:focus-visible{outline:2px solid var(--pink);outline-offset:4px}
@media (max-width:1100px){.control-room{grid-template-columns:210px minmax(430px,1fr) 210px;gap:15px}.signal-grid{grid-template-columns:repeat(3,1fr)}.hero h1{font-size:51px}.core-sphere{width:190px;height:190px}}
@media (max-width:820px){.page{width:calc(100% - 32px)}.control-room{display:flex;flex-direction:column;align-items:stretch;gap:12px;padding-top:38px}.left-deck{order:2;max-width:680px}.core-stage{order:1;height:560px;min-height:0;margin:0 -10px}.right-deck{order:3}.signals-section{order:4}.control-room{min-height:0}.readouts{max-width:500px}.right-deck{display:grid;grid-template-columns:1fr 1.1fr;gap:20px;align-items:start}.right-deck>.deck-label{grid-column:1/-1}.system-box{margin-top:0}.relay-title{margin-top:0}.signal-grid{grid-template-columns:repeat(3,1fr)}}
@media (max-width:560px){.hud-top{height:62px}.brand-copy small{display:none}.top-status{font-size:8px;gap:8px}.top-status span:first-child{display:none}.control-room{padding:36px 0 35px}.left-deck h1{font-size:clamp(48px,15vw,70px);margin-top:17px}.lede{font-size:13px}.actions{margin-top:21px}.readouts{margin-top:28px;gap:10px}.readout b{font-size:15px}.readout small{font-size:7px}.core-stage{height:455px;margin:0 -8px}.stage-caption{font-size:8px}.stage-coordinates{font-size:7px}.orbit-core{width:84%;transform:rotateX(59deg) rotateZ(calc(var(--mx)*3deg));}.core-sphere{width:158px;height:158px}.core-eye{font-size:12px}.core-eye small{font-size:6px}.node{font-size:7px;padding:6px 7px}.telemetry{font-size:7px;padding:6px}.telemetry.left{left:0;top:22%}.telemetry.right{right:0;top:24%}.telemetry.bottom{left:0;bottom:8%}.signal-console{bottom:1%;width:83%;padding:9px 10px}.signal-console strong{font-size:12px}.right-deck{display:block}.system-box{margin-top:12px}.relay-title{margin-top:24px}.relay-card{padding:11px}.signals-section{padding-top:21px}.signals-head{align-items:start;flex-direction:column;gap:7px}.signals-head h2{font-size:24px}.filters{gap:5px}.filter{padding:7px 9px}.signal-grid{grid-template-columns:repeat(2,1fr);gap:6px}.signal-card{min-height:119px;padding:12px}.signal-card strong{font-size:15px}.signal-card small{font-size:9px}.footer{flex-direction:column;gap:8px}}
@media (prefers-reduced-motion:reduce){html{scroll-behavior:auto}.orbit-ring,.core-sphere:after{animation:none}.action,.relay-card,.signal-card{transition:none}}
</style>
</head>
<body class="scene">
<canvas id="starfield" aria-hidden="true"></canvas>
<div class="scanline" aria-hidden="true"></div>
<div class="page">
  <header class="hud-top"><a class="brand" href="#top" aria-label="星港游戏厅首页"><span class="brand-core">09</span><span class="brand-copy"><b>星港游戏厅</b><small>STARPORT / SIGNAL CONTROL</small></span></a><div class="top-status"><span>SECTOR 09 · UPLINK 77.21</span><span><i class="online-dot"></i>SYSTEM <b>ONLINE</b></span></div></header>
  <main id="top">
    <section class="control-room" aria-labelledby="hero-title">
      <div class="left-deck"><div class="eyebrow">UNAUTHORIZED FUN / PORT 09</div><h1 id="hero-title">找到你的<br><span>下一次跃迁</span></h1><p class="lede">星港深夜信号站已上线。<br>这里有 <b>29 枚游戏信号</b>，每一枚都通往一段不同的旅程。</p><div class="actions"><a class="action primary" href="#signals">扫描信号 <span>↓</span></a><a class="action" href="__HERO_URL__">直接接入 <span>↗</span></a></div><div class="readouts"><div class="readout"><b>29</b><small>ACTIVE NODES</small></div><div class="readout"><b>24 / 7</b><small>UPLINK STATUS</small></div><div class="readout"><b>01 COIN</b><small>INITIALIZE</small></div><div class="readout"><b>12ms</b><small>LATENCY</small></div></div></div>
      <div class="core-stage"><span class="stage-caption">HOLOGRAPHIC COMMAND DECK / LIVE FEED</span><span class="stage-coordinates">X 09.771 · Y 44.203 · Z 00.013</span><div class="stage-cross"></div><div class="orbit-core"><div class="orbit-ring"></div><div class="orbit-ring two"></div><div class="orbit-ring three"></div><i class="node a">SIG-29 / CASE</i><i class="node b">SIG-13 / SIM</i><i class="node c">SIG-24 / ARCADE</i><div class="telemetry left"><b>FIELD / NIGHT-09</b>PARTICLES 128<br>DRIFT 0.0037</div><div class="telemetry right"><b>CORE / STABLE</b>WAVEFORM ∿ 98.4%<br>LOCKS 03 / 29</div><div class="telemetry bottom"><b>SCAN BEAM ∿∿∿</b>SEARCHING FOR PLAYERS</div><div class="core-sphere"></div><div class="core-eye">SIGNAL<br><small>READY TO LOCK</small></div><a class="signal-console cab" href="__HERO_URL__" data-name="霓虹幸存者" data-tag="NEON SURVIVORS" aria-label="锁定并进入霓虹幸存者"><span class="lock-mark">⌁</span><span><small>TARGET LOCKED / NEW SIGNAL</small><strong id="lock-name">霓虹幸存者</strong></span><em>READY ↗</em></a></div></div>
      <aside class="right-deck"><div class="deck-label"><span>MISSION CONTROL / 09</span><b><i class="online-dot"></i>LIVE</b></div><div class="system-box"><h2>CORE TELEMETRY</h2><p>全息信号核心正在扫描可玩的世界。悬停或触摸任意信号，改变锁定目标。</p><div class="bar"><i></i></div><div class="metric-line"><span>SCAN PROGRESS</span><b>76.2%</b></div></div><div><div class="relay-title">RECOMMENDED RELAYS / 03</div><div class="relay-list">__RELAYS__</div></div></aside>
    </section>
    <section class="signals-section" id="signals" aria-labelledby="signals-title"><div class="signals-head"><h2 id="signals-title">全部游戏信号</h2><p>SELECT FREQUENCY / 29 ACTIVE NODES</p></div><div class="filters" role="group" aria-label="按类型筛选"><button class="filter active" data-filter="全部">全部信号</button>__FILTERS__</div><div class="signal-grid">__SIGNALS__<div class="empty" hidden>该频段没有回应，换一个信号。</div></div></section>
  </main>
  <footer class="footer"><span>STARPORT ARCADE OS / <b>ALL SYSTEMS ONLINE</b></span><span>LOCK A SIGNAL · ENTER THE GAME · MAKE YOUR OWN ROUTE</span></footer>
</div>
<script>
(function(){
  const canvas=document.getElementById('starfield'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let w=0,h=0,dpr=1,stars=[],pointer={x:.5,y:.5};
  function resize(){dpr=Math.min(devicePixelRatio||1,1.5);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const total=w<600?110:210;stars=Array.from({length:total},(_,i)=>({x:Math.random()*w,y:Math.random()*h,z:.15+Math.random()*.85,r:.25+Math.random()*1.3,v:.02+Math.random()*.11,c:i%13===0?'pink':i%9===0?'violet':'cyan'}));}
  function draw(ms){const t=reduced?0:ms*.001;ctx.clearRect(0,0,w,h);ctx.fillStyle='#02040c';ctx.fillRect(0,0,w,h);const dx=(pointer.x-.5)*22,dy=(pointer.y-.5)*14;stars.forEach((s,i)=>{let x=(s.x+dx*s.z+(reduced?0:t*s.v*12))%w;if(x<0)x+=w;const y=s.y+dy*s.z,p=.55+.45*Math.sin(t*1.8+i);ctx.fillStyle=s.c==='pink'?`rgba(255,63,185,${.22+p*.45})`:s.c==='violet'?`rgba(152,124,255,${.2+p*.4})`:`rgba(84,243,255,${.16+p*.38})`;ctx.beginPath();ctx.arc(x,y,s.r*(.6+s.z),0,Math.PI*2);ctx.fill();if(s.z>.75){ctx.globalAlpha=.15;ctx.strokeStyle=ctx.fillStyle;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-dx*.7,y-dy*.7);ctx.stroke();ctx.globalAlpha=1;}});const horizon=h*.73;ctx.strokeStyle='rgba(84,243,255,.055)';for(let i=-12;i<13;i++){ctx.beginPath();ctx.moveTo(w/2+i*62,horizon);ctx.lineTo(w/2+i*190,h);ctx.stroke();}for(let y=horizon;y<h;y+=34){ctx.globalAlpha=.05+((y-horizon)/(h-horizon))*.1;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.globalAlpha=1;if(!reduced)requestAnimationFrame(draw);}
  addEventListener('resize',resize);addEventListener('pointermove',e=>{pointer.x=e.clientX/innerWidth;pointer.y=e.clientY/innerHeight;document.documentElement.style.setProperty('--mx',pointer.x-.5);document.documentElement.style.setProperty('--my',pointer.y-.5)});resize();requestAnimationFrame(draw);
  const lock=document.getElementById('lock-name'),caption=document.querySelector('.signal-console small');document.querySelectorAll('.cab[data-name]').forEach(card=>{const update=()=>{if(lock)lock.textContent=card.dataset.name;if(caption)caption.textContent='TARGET LOCKED / '+card.dataset.tag};card.addEventListener('pointerenter',update);card.addEventListener('focus',update);});
  const filters=[...document.querySelectorAll('.filter')],cards=[...document.querySelectorAll('.signal-card')],empty=document.querySelector('.empty');filters.forEach(f=>f.addEventListener('click',()=>{const v=f.dataset.filter;filters.forEach(x=>x.classList.toggle('active',x===f));let n=0;cards.forEach(card=>{const show=v==='全部'||card.dataset.category===v;card.hidden=!show;if(show)n++;});empty.hidden=n>0;document.getElementById('signals-title').textContent=v==='全部'?'全部游戏信号':v+' · 信号';}));
})();
</script>
</body>
</html>
'''
html = html.replace('__HERO_URL__', hero['url']).replace('__RELAYS__', relays).replace('__FILTERS__', filters).replace('__SIGNALS__', signals)
(ROOT / 'arcade.html').write_text(html)
print(f'generated signal control arcade with {len(games)} nodes and {len(categories)} frequencies')
