const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const html = fs.readFileSync(__dirname + '/starport-investigator.html', 'utf8');
const source = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const elements = new Proxy({}, {get(target,id){
  if(!target[id]) target[id]={textContent:'',innerHTML:'',value:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll(){return []}};
  return target[id];
}});
const document={getElementById:id=>elements[id],querySelectorAll:()=>[]};
const sandbox={document,localStorage:{starportInvestBest:'0'},location:{href:''},console,Math,Set,Array,Number,String};
vm.createContext(sandbox); vm.runInContext(source,sandbox);
assert.strictEqual(typeof sandbox.buildTimeline,'function','timeline builder must exist');
assert.strictEqual(typeof sandbox.inspectTimeline,'function','timeline inspector must exist');
const timeline=sandbox.buildTimeline(sandbox.CASES[0], 'ctl', 17);
assert.ok(timeline.length>=4,'timeline must expose at least four time points');
assert.ok(timeline.some(x=>x.critical),'timeline must contain a decisive time point');
const ordinary=timeline.find(x=>!x.critical);
const decisive=timeline.find(x=>x.critical);
const ordinaryResult=sandbox.inspectTimeline(timeline,ordinary.id);
const decisiveResult=sandbox.inspectTimeline(timeline,decisive.id);
assert.ok(ordinaryResult.frame && decisiveResult.frame,'every selected frame must render a frame result');
assert.notStrictEqual(ordinaryResult.clue,decisiveResult.clue,'decisive frame must reveal different evidence');
assert.strictEqual(ordinaryResult.critical,false,'ordinary frame must not be decisive');
assert.strictEqual(decisiveResult.critical,true,'critical frame must be decisive');
assert.ok(decisiveResult.variantEffect && decisiveResult.variantEffect.length>5,'decisive frame must expose the case variable');
const beacon=sandbox.buildTimeline(sandbox.CASES.find(x=>x.id===8),'beacon8',23);
assert.strictEqual(beacon.length,5,'beacon timeline must expose five frames');
assert.ok(beacon.some(x=>x.critical),'beacon timeline must contain a decisive frame');
console.log('TIMELINE-BEHAVIOR-OK');
