const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const html = fs.readFileSync(__dirname + '/starport-investigator.html', 'utf8');
const source = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const elements = new Proxy({}, {get(target,id){
  if(!target[id]) target[id]={textContent:'',innerHTML:'',value:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll(){return []}};
  return target[id];
}});
const document={getElementById:id=>elements[id],querySelectorAll:()=>[]};
const sandbox={document,localStorage:{starportInvestBest:'0'},location:{href:''},console,Math,Set,Array,Number,String};
vm.createContext(sandbox); vm.runInContext(source,sandbox);
assert.strictEqual(typeof sandbox.resolveSearchAction,'function','search resolver must exist');
assert.strictEqual(typeof sandbox.buildSearchPlan,'function','search plan builder must exist');
assert.strictEqual(typeof sandbox.buildCaseVariant,'function','case variant builder must exist');
const variantA=sandbox.buildCaseVariant(sandbox.CASES[0], 17);
const variantB=sandbox.buildCaseVariant(sandbox.CASES[0], 18);
assert.ok(variantA.solution.culprit!==variantB.solution.culprit || variantA.solution.motive!==variantB.solution.motive,'different seeds must change a case conclusion');
const clueA=variantA.locations.find(x=>x.key==='vera').clues[0];
const clueB=variantB.locations.find(x=>x.key==='vera').clues[0];
assert.notStrictEqual(clueA,clueB,'different seeds must change a key evidence clue');
const plan=sandbox.buildSearchPlan(sandbox.CASES[0], 17);
assert.ok(plan.actions.length>=3,'a searchable location must expose three actions');
assert.ok(plan.maxActions>=2,'search must have a limited action budget');
const scan=sandbox.resolveSearchAction(plan.location,'scan',plan.variant);
const observe=sandbox.resolveSearchAction(plan.location,'observe',plan.variant);
assert.ok(scan.clue && observe.clue,'each search action must reveal a clue');
assert.notStrictEqual(scan.clue,observe.clue,'different tools must reveal different evidence');
assert.ok(scan.variantEffect && scan.variantEffect.length>5,'variant must change an evidence result');
assert.strictEqual(sandbox.canSubmitVerdict(1),false,'one clue must not be enough to submit');
assert.strictEqual(sandbox.canSubmitVerdict(3),true,'three clues must unlock submission');
console.log('SEARCH-BEHAVIOR-OK');
