const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const html = fs.readFileSync(__dirname + '/starport-investigator.html', 'utf8');
const source = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const elements = new Proxy({}, {get(target,id){
  if(!target[id]) target[id]={textContent:'',innerHTML:'',value:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll(){return []}};
  return target[id];
}});
const document={getElementById:id=>elements[id],querySelectorAll:()=>[]};
const sandbox={document,localStorage:{starportInvestBest:'0'},location:{href:''},console,Math,Set,Array,Number,String};
vm.createContext(sandbox); vm.runInContext(source,sandbox);
assert.strictEqual(typeof sandbox.deriveEvidenceImpact,'function','evidence impact derivation must exist');
const matched=[{traceKey:'cargo:fingerprint',matched:true,suspect:'老周',location:'货舱',action:'物证比对'}];
const excluded=[{excluded:true,suspect:'凯拉',location:'货舱',action:'物证排除'}];
const yes=sandbox.deriveEvidenceImpact(sandbox.CASES[0],matched);
const no=sandbox.deriveEvidenceImpact(sandbox.CASES[0],excluded);
assert.strictEqual(yes.confirmedSuspect,'老周','matched evidence must confirm the correct suspect');
assert.strictEqual(yes.evidenceStrength,'verified','matched evidence must be verified');
assert.strictEqual(yes.ending,'evidence-closed','matched evidence must unlock evidence-closed ending');
assert.strictEqual(no.confirmedSuspect,null,'excluded evidence must not confirm a suspect');
assert.strictEqual(no.ending,'incomplete-chain','excluded evidence must not close the chain');
const stateOnly=sandbox.deriveEvidenceImpact(sandbox.CASES[0],[], '老周');
assert.strictEqual(stateOnly.evidenceStrength,'verified','stable confirmed state must verify evidence');
assert.strictEqual(stateOnly.ending,'evidence-closed','stable confirmed state must close the chain');
assert.ok(yes.statusText.includes('老周'),'deduction status must name the confirmed suspect');
assert.strictEqual(typeof sandbox.evaluateVerdict,'function','verdict evaluator must exist');
assert.strictEqual(sandbox.evaluateVerdict(true,true,yes).ending,'evidence-closed','verified evidence must change the ending');
assert.strictEqual(sandbox.evaluateVerdict(true,true,no).ending,'logical-only','without a match the ending must remain logical-only');
console.log('EVIDENCE-IMPACT-OK');
